// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "driver/pkg/endpoint"
	"pkg/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	getDriverInfo grpc.Handler
	takeOrder     grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.DriverServer {
	return &grpcServer{
		getDriverInfo: makeGetDriverInfoHandler(endpoints, options["GetDriverInfo"]),
		takeOrder:     makeTakeOrderHandler(endpoints, options["TakeOrder"]),
	}
}
