// Code generated by protoc-gen-go. DO NOT EDIT.
// source: billing.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BillMsg struct {
	BillNum              int64    `protobuf:"varint,1,opt,name=bill_num,json=billNum,proto3" json:"bill_num,omitempty"`
	Price                float32  `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	StartTime            int64    `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64    `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Origin               string   `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination          string   `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
	PassengerName        string   `protobuf:"bytes,7,opt,name=passenger_name,json=passengerName,proto3" json:"passenger_name,omitempty"`
	DriverName           string   `protobuf:"bytes,8,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	Payed                bool     `protobuf:"varint,9,opt,name=payed,proto3" json:"payed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BillMsg) Reset()         { *m = BillMsg{} }
func (m *BillMsg) String() string { return proto.CompactTextString(m) }
func (*BillMsg) ProtoMessage()    {}
func (*BillMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{0}
}

func (m *BillMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BillMsg.Unmarshal(m, b)
}
func (m *BillMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BillMsg.Marshal(b, m, deterministic)
}
func (m *BillMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BillMsg.Merge(m, src)
}
func (m *BillMsg) XXX_Size() int {
	return xxx_messageInfo_BillMsg.Size(m)
}
func (m *BillMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BillMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BillMsg proto.InternalMessageInfo

func (m *BillMsg) GetBillNum() int64 {
	if m != nil {
		return m.BillNum
	}
	return 0
}

func (m *BillMsg) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BillMsg) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *BillMsg) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *BillMsg) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *BillMsg) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *BillMsg) GetPassengerName() string {
	if m != nil {
		return m.PassengerName
	}
	return ""
}

func (m *BillMsg) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *BillMsg) GetPayed() bool {
	if m != nil {
		return m.Payed
	}
	return false
}

type GenBillReq struct {
	TripMsg              *TripMsg `protobuf:"bytes,1,opt,name=trip_msg,json=tripMsg,proto3" json:"trip_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenBillReq) Reset()         { *m = GenBillReq{} }
func (m *GenBillReq) String() string { return proto.CompactTextString(m) }
func (*GenBillReq) ProtoMessage()    {}
func (*GenBillReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{1}
}

func (m *GenBillReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenBillReq.Unmarshal(m, b)
}
func (m *GenBillReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenBillReq.Marshal(b, m, deterministic)
}
func (m *GenBillReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenBillReq.Merge(m, src)
}
func (m *GenBillReq) XXX_Size() int {
	return xxx_messageInfo_GenBillReq.Size(m)
}
func (m *GenBillReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GenBillReq.DiscardUnknown(m)
}

var xxx_messageInfo_GenBillReq proto.InternalMessageInfo

func (m *GenBillReq) GetTripMsg() *TripMsg {
	if m != nil {
		return m.TripMsg
	}
	return nil
}

type GenBillResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	BillMsg              *BillMsg `protobuf:"bytes,2,opt,name=bill_msg,json=billMsg,proto3" json:"bill_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenBillResp) Reset()         { *m = GenBillResp{} }
func (m *GenBillResp) String() string { return proto.CompactTextString(m) }
func (*GenBillResp) ProtoMessage()    {}
func (*GenBillResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{2}
}

func (m *GenBillResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenBillResp.Unmarshal(m, b)
}
func (m *GenBillResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenBillResp.Marshal(b, m, deterministic)
}
func (m *GenBillResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenBillResp.Merge(m, src)
}
func (m *GenBillResp) XXX_Size() int {
	return xxx_messageInfo_GenBillResp.Size(m)
}
func (m *GenBillResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GenBillResp.DiscardUnknown(m)
}

var xxx_messageInfo_GenBillResp proto.InternalMessageInfo

func (m *GenBillResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *GenBillResp) GetBillMsg() *BillMsg {
	if m != nil {
		return m.BillMsg
	}
	return nil
}

type GetBillReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBillReq) Reset()         { *m = GetBillReq{} }
func (m *GetBillReq) String() string { return proto.CompactTextString(m) }
func (*GetBillReq) ProtoMessage()    {}
func (*GetBillReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{3}
}

func (m *GetBillReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBillReq.Unmarshal(m, b)
}
func (m *GetBillReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBillReq.Marshal(b, m, deterministic)
}
func (m *GetBillReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBillReq.Merge(m, src)
}
func (m *GetBillReq) XXX_Size() int {
	return xxx_messageInfo_GetBillReq.Size(m)
}
func (m *GetBillReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBillReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBillReq proto.InternalMessageInfo

func (m *GetBillReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetBillResp struct {
	BillList             []*BillMsg `protobuf:"bytes,1,rep,name=bill_list,json=billList,proto3" json:"bill_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetBillResp) Reset()         { *m = GetBillResp{} }
func (m *GetBillResp) String() string { return proto.CompactTextString(m) }
func (*GetBillResp) ProtoMessage()    {}
func (*GetBillResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{4}
}

func (m *GetBillResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBillResp.Unmarshal(m, b)
}
func (m *GetBillResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBillResp.Marshal(b, m, deterministic)
}
func (m *GetBillResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBillResp.Merge(m, src)
}
func (m *GetBillResp) XXX_Size() int {
	return xxx_messageInfo_GetBillResp.Size(m)
}
func (m *GetBillResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBillResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetBillResp proto.InternalMessageInfo

func (m *GetBillResp) GetBillList() []*BillMsg {
	if m != nil {
		return m.BillList
	}
	return nil
}

func init() {
	proto.RegisterType((*BillMsg)(nil), "pb.BillMsg")
	proto.RegisterType((*GenBillReq)(nil), "pb.GenBillReq")
	proto.RegisterType((*GenBillResp)(nil), "pb.GenBillResp")
	proto.RegisterType((*GetBillReq)(nil), "pb.GetBillReq")
	proto.RegisterType((*GetBillResp)(nil), "pb.GetBillResp")
}

func init() {
	proto.RegisterFile("billing.proto", fileDescriptor_958db8ba491a6b57)
}

var fileDescriptor_958db8ba491a6b57 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0x4d, 0x8b, 0xd4, 0x40,
	0x10, 0x25, 0x19, 0x37, 0x1f, 0x15, 0x76, 0x84, 0x46, 0xb4, 0x5d, 0x10, 0x43, 0x60, 0x25, 0x78,
	0xc8, 0x61, 0x15, 0xbc, 0xef, 0x45, 0x04, 0x67, 0x0e, 0x71, 0xee, 0x21, 0x31, 0x4d, 0x28, 0x48,
	0x3a, 0x6d, 0x77, 0x67, 0xc0, 0xff, 0xe0, 0x8f, 0x96, 0xea, 0xce, 0x64, 0x74, 0x6e, 0xfd, 0xaa,
	0x5e, 0xbd, 0xaa, 0x7a, 0x5d, 0x70, 0xdf, 0xe1, 0x38, 0xa2, 0x1c, 0x2a, 0xa5, 0x67, 0x3b, 0xb3,
	0x50, 0x75, 0x0f, 0x60, 0x35, 0x2a, 0x8f, 0x8b, 0x3f, 0x21, 0xc4, 0xcf, 0x38, 0x8e, 0x07, 0x33,
	0xb0, 0xb7, 0x90, 0x10, 0xb9, 0x91, 0xcb, 0xc4, 0x83, 0x3c, 0x28, 0x77, 0x75, 0x4c, 0xf8, 0xb8,
	0x4c, 0xec, 0x15, 0xdc, 0x29, 0x8d, 0x3f, 0x05, 0x0f, 0xf3, 0xa0, 0x0c, 0x6b, 0x0f, 0xd8, 0x3b,
	0x00, 0x63, 0x5b, 0x6d, 0x1b, 0x8b, 0x93, 0xe0, 0x3b, 0x57, 0x92, 0xba, 0xc8, 0x09, 0x27, 0x41,
	0x7a, 0x42, 0xf6, 0x3e, 0xf9, 0xc2, 0xeb, 0x09, 0xd9, 0xbb, 0xd4, 0x6b, 0x88, 0x66, 0x8d, 0x03,
	0x4a, 0x7e, 0x97, 0x07, 0x65, 0x5a, 0xaf, 0x88, 0xe5, 0x90, 0xf5, 0xc2, 0x58, 0x94, 0xad, 0xc5,
	0x59, 0xf2, 0xc8, 0x25, 0xff, 0x0d, 0xb1, 0x47, 0xd8, 0xab, 0xd6, 0x18, 0x21, 0x07, 0xa1, 0x1b,
	0xd9, 0x4e, 0x82, 0xc7, 0x8e, 0x74, 0xbf, 0x45, 0x8f, 0xed, 0x24, 0xd8, 0x7b, 0xc8, 0x7a, 0x8d,
	0xe7, 0x0b, 0x27, 0x71, 0x1c, 0xf0, 0x21, 0x47, 0xa0, 0x8d, 0xda, 0xdf, 0xa2, 0xe7, 0x69, 0x1e,
	0x94, 0x49, 0xed, 0x41, 0xf1, 0x19, 0xe0, 0xab, 0x90, 0x64, 0x48, 0x2d, 0x7e, 0xb1, 0x0f, 0x90,
	0x90, 0x55, 0xcd, 0x64, 0x06, 0x67, 0x48, 0xf6, 0x94, 0x55, 0xaa, 0xab, 0x4e, 0x1a, 0xd5, 0xc1,
	0x0c, 0x75, 0x6c, 0xfd, 0xa3, 0x38, 0x40, 0xb6, 0x55, 0x19, 0x45, 0xcb, 0x19, 0xdb, 0xda, 0xc5,
	0xb8, 0xa2, 0xa4, 0x5e, 0x11, 0xc9, 0x39, 0x7f, 0x49, 0x2e, 0xbc, 0xca, 0xad, 0xf6, 0x7b, 0xb3,
	0x49, 0xee, 0x91, 0x86, 0xb0, 0x97, 0x21, 0xde, 0x40, 0xbc, 0x18, 0xa1, 0x1b, 0xec, 0xd7, 0x4f,
	0x89, 0x08, 0x7e, 0xeb, 0x8b, 0x2f, 0xd4, 0xd5, 0x6e, 0x5d, 0x4b, 0x48, 0x9d, 0xfa, 0x88, 0xc6,
	0xf2, 0x20, 0xdf, 0xdd, 0xca, 0xbb, 0xde, 0xdf, 0xd1, 0xd8, 0xa7, 0x11, 0xf6, 0xcf, 0xfe, 0x28,
	0x7e, 0x08, 0x7d, 0xa6, 0x8f, 0xfc, 0x08, 0xf1, 0xba, 0x00, 0xdb, 0x53, 0xcd, 0xd5, 0x83, 0x87,
	0x97, 0xff, 0x61, 0xa3, 0x58, 0xb5, 0xb5, 0x25, 0xb1, 0x0b, 0xdf, 0xde, 0xf0, 0xb7, 0xb9, 0xba,
	0xc8, 0x1d, 0xda, 0xa7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xab, 0xf8, 0x25, 0x33, 0x89, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BillingServiceClient interface {
	GenBill(ctx context.Context, in *GenBillReq, opts ...grpc.CallOption) (*GenBillResp, error)
	GetBillList(ctx context.Context, in *GetBillReq, opts ...grpc.CallOption) (*GetBillResp, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) GenBill(ctx context.Context, in *GenBillReq, opts ...grpc.CallOption) (*GenBillResp, error) {
	out := new(GenBillResp)
	err := c.cc.Invoke(ctx, "/pb.BillingService/GenBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetBillList(ctx context.Context, in *GetBillReq, opts ...grpc.CallOption) (*GetBillResp, error) {
	out := new(GetBillResp)
	err := c.cc.Invoke(ctx, "/pb.BillingService/GetBillList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
type BillingServiceServer interface {
	GenBill(context.Context, *GenBillReq) (*GenBillResp, error)
	GetBillList(context.Context, *GetBillReq) (*GetBillResp, error)
}

// UnimplementedBillingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBillingServiceServer struct {
}

func (*UnimplementedBillingServiceServer) GenBill(ctx context.Context, req *GenBillReq) (*GenBillResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenBill not implemented")
}
func (*UnimplementedBillingServiceServer) GetBillList(ctx context.Context, req *GetBillReq) (*GetBillResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBillList not implemented")
}

func RegisterBillingServiceServer(s *grpc.Server, srv BillingServiceServer) {
	s.RegisterService(&_BillingService_serviceDesc, srv)
}

func _BillingService_GenBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenBillReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GenBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BillingService/GenBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GenBill(ctx, req.(*GenBillReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetBillList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetBillList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BillingService/GetBillList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetBillList(ctx, req.(*GetBillReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _BillingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenBill",
			Handler:    _BillingService_GenBill_Handler,
		},
		{
			MethodName: "GetBillList",
			Handler:    _BillingService_GetBillList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing.proto",
}
