// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NoticeTripRequest struct {
	TripMsg              *TripMsg `protobuf:"bytes,1,opt,name=trip_msg,json=tripMsg,proto3" json:"trip_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeTripRequest) Reset()         { *m = NoticeTripRequest{} }
func (m *NoticeTripRequest) String() string { return proto.CompactTextString(m) }
func (*NoticeTripRequest) ProtoMessage()    {}
func (*NoticeTripRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{0}
}

func (m *NoticeTripRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeTripRequest.Unmarshal(m, b)
}
func (m *NoticeTripRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeTripRequest.Marshal(b, m, deterministic)
}
func (m *NoticeTripRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeTripRequest.Merge(m, src)
}
func (m *NoticeTripRequest) XXX_Size() int {
	return xxx_messageInfo_NoticeTripRequest.Size(m)
}
func (m *NoticeTripRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeTripRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeTripRequest proto.InternalMessageInfo

func (m *NoticeTripRequest) GetTripMsg() *TripMsg {
	if m != nil {
		return m.TripMsg
	}
	return nil
}

type NoticeTripReply struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeTripReply) Reset()         { *m = NoticeTripReply{} }
func (m *NoticeTripReply) String() string { return proto.CompactTextString(m) }
func (*NoticeTripReply) ProtoMessage()    {}
func (*NoticeTripReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{1}
}

func (m *NoticeTripReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeTripReply.Unmarshal(m, b)
}
func (m *NoticeTripReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeTripReply.Marshal(b, m, deterministic)
}
func (m *NoticeTripReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeTripReply.Merge(m, src)
}
func (m *NoticeTripReply) XXX_Size() int {
	return xxx_messageInfo_NoticeTripReply.Size(m)
}
func (m *NoticeTripReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeTripReply.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeTripReply proto.InternalMessageInfo

func (m *NoticeTripReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *NoticeTripReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type NoticeBillRequest struct {
	BillMsg              *BillMsg `protobuf:"bytes,1,opt,name=bill_msg,json=billMsg,proto3" json:"bill_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeBillRequest) Reset()         { *m = NoticeBillRequest{} }
func (m *NoticeBillRequest) String() string { return proto.CompactTextString(m) }
func (*NoticeBillRequest) ProtoMessage()    {}
func (*NoticeBillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{2}
}

func (m *NoticeBillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeBillRequest.Unmarshal(m, b)
}
func (m *NoticeBillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeBillRequest.Marshal(b, m, deterministic)
}
func (m *NoticeBillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeBillRequest.Merge(m, src)
}
func (m *NoticeBillRequest) XXX_Size() int {
	return xxx_messageInfo_NoticeBillRequest.Size(m)
}
func (m *NoticeBillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeBillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeBillRequest proto.InternalMessageInfo

func (m *NoticeBillRequest) GetBillMsg() *BillMsg {
	if m != nil {
		return m.BillMsg
	}
	return nil
}

type NoticeBillReply struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeBillReply) Reset()         { *m = NoticeBillReply{} }
func (m *NoticeBillReply) String() string { return proto.CompactTextString(m) }
func (*NoticeBillReply) ProtoMessage()    {}
func (*NoticeBillReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{3}
}

func (m *NoticeBillReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeBillReply.Unmarshal(m, b)
}
func (m *NoticeBillReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeBillReply.Marshal(b, m, deterministic)
}
func (m *NoticeBillReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeBillReply.Merge(m, src)
}
func (m *NoticeBillReply) XXX_Size() int {
	return xxx_messageInfo_NoticeBillReply.Size(m)
}
func (m *NoticeBillReply) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeBillReply.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeBillReply proto.InternalMessageInfo

func (m *NoticeBillReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *NoticeBillReply) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*NoticeTripRequest)(nil), "pb.NoticeTripRequest")
	proto.RegisterType((*NoticeTripReply)(nil), "pb.NoticeTripReply")
	proto.RegisterType((*NoticeBillRequest)(nil), "pb.NoticeBillRequest")
	proto.RegisterType((*NoticeBillReply)(nil), "pb.NoticeBillReply")
}

func init() {
	proto.RegisterFile("notification.proto", fileDescriptor_736a457d4a5efa07)
}

var fileDescriptor_736a457d4a5efa07 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xb1, 0x4b, 0xc5, 0x30,
	0x10, 0x87, 0xc9, 0x13, 0x9e, 0xcf, 0x7b, 0x8a, 0x1a, 0x51, 0xa4, 0x53, 0xe9, 0x20, 0x9d, 0x3a,
	0xd4, 0x45, 0xe8, 0xe6, 0x6e, 0x87, 0xe0, 0x2e, 0x4d, 0xa9, 0xe5, 0x20, 0x36, 0xb1, 0xb9, 0x0e,
	0xae, 0xfe, 0xe5, 0x72, 0x8d, 0xb4, 0xa1, 0x4e, 0x6e, 0x77, 0xe1, 0xbe, 0x7c, 0x77, 0x3f, 0x90,
	0x83, 0x25, 0x7c, 0xc7, 0xb6, 0x21, 0xb4, 0x43, 0xe1, 0x46, 0x4b, 0x56, 0xee, 0x9c, 0x4e, 0x80,
	0x46, 0x74, 0xa1, 0x4f, 0x2e, 0x34, 0x1a, 0x83, 0x43, 0x1f, 0xda, 0xac, 0x82, 0xeb, 0xda, 0x12,
	0xb6, 0xdd, 0xeb, 0x88, 0x4e, 0x75, 0x9f, 0x53, 0xe7, 0x49, 0x3e, 0xc0, 0x81, 0x89, 0xb7, 0x0f,
	0xdf, 0xdf, 0x8b, 0x54, 0xe4, 0xc7, 0xf2, 0x58, 0x38, 0x5d, 0xf0, 0xc8, 0x8b, 0xef, 0xd5, 0x29,
	0x85, 0x22, 0xab, 0xe0, 0x32, 0x86, 0x9d, 0xf9, 0x92, 0x77, 0xb0, 0xf7, 0xd4, 0xd0, 0xe4, 0x67,
	0xf0, 0xa0, 0x7e, 0x3b, 0x79, 0x05, 0x27, 0xfc, 0xdb, 0x2e, 0x15, 0xf9, 0x99, 0xe2, 0x72, 0x35,
	0x3f, 0xa3, 0x31, 0x91, 0x99, 0xf7, 0xdb, 0x9a, 0x79, 0x64, 0x36, 0xeb, 0x50, 0xac, 0xe6, 0x00,
	0xff, 0xcb, 0x5c, 0x7e, 0x0b, 0x38, 0xaf, 0xa3, 0xa4, 0xe4, 0x13, 0xc0, 0x7a, 0x87, 0xbc, 0x65,
	0xe3, 0x9f, 0x50, 0x92, 0x9b, 0xed, 0x33, 0x4b, 0x17, 0x92, 0xf7, 0x88, 0xc9, 0xe8, 0xa8, 0x98,
	0x5c, 0xd6, 0xd5, 0xfb, 0x39, 0xff, 0xc7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xe8, 0x86,
	0x8f, 0xb4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NotificationClient is the client API for Notification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationClient interface {
	NoticeTrip(ctx context.Context, in *NoticeTripRequest, opts ...grpc.CallOption) (*NoticeTripReply, error)
	NoticeBill(ctx context.Context, in *NoticeBillRequest, opts ...grpc.CallOption) (*NoticeBillReply, error)
}

type notificationClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationClient(cc grpc.ClientConnInterface) NotificationClient {
	return &notificationClient{cc}
}

func (c *notificationClient) NoticeTrip(ctx context.Context, in *NoticeTripRequest, opts ...grpc.CallOption) (*NoticeTripReply, error) {
	out := new(NoticeTripReply)
	err := c.cc.Invoke(ctx, "/pb.Notification/NoticeTrip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) NoticeBill(ctx context.Context, in *NoticeBillRequest, opts ...grpc.CallOption) (*NoticeBillReply, error) {
	out := new(NoticeBillReply)
	err := c.cc.Invoke(ctx, "/pb.Notification/NoticeBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServer is the server API for Notification service.
type NotificationServer interface {
	NoticeTrip(context.Context, *NoticeTripRequest) (*NoticeTripReply, error)
	NoticeBill(context.Context, *NoticeBillRequest) (*NoticeBillReply, error)
}

// UnimplementedNotificationServer can be embedded to have forward compatible implementations.
type UnimplementedNotificationServer struct {
}

func (*UnimplementedNotificationServer) NoticeTrip(ctx context.Context, req *NoticeTripRequest) (*NoticeTripReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NoticeTrip not implemented")
}
func (*UnimplementedNotificationServer) NoticeBill(ctx context.Context, req *NoticeBillRequest) (*NoticeBillReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NoticeBill not implemented")
}

func RegisterNotificationServer(s *grpc.Server, srv NotificationServer) {
	s.RegisterService(&_Notification_serviceDesc, srv)
}

func _Notification_NoticeTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).NoticeTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Notification/NoticeTrip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).NoticeTrip(ctx, req.(*NoticeTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_NoticeBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).NoticeBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Notification/NoticeBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).NoticeBill(ctx, req.(*NoticeBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notification_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Notification",
	HandlerType: (*NotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NoticeTrip",
			Handler:    _Notification_NoticeTrip_Handler,
		},
		{
			MethodName: "NoticeBill",
			Handler:    _Notification_NoticeBill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}
