// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	service "billing/pkg/service"
	endpoint "github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	GenBillEndpoint     endpoint.Endpoint
	GetBillListEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.BillingService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		GenBillEndpoint:     MakeGenBillEndpoint(s),
		GetBillListEndpoint: MakeGetBillListEndpoint(s),
	}
	for _, m := range mdw["GenBill"] {
		eps.GenBillEndpoint = m(eps.GenBillEndpoint)
	}
	for _, m := range mdw["GetBillList"] {
		eps.GetBillListEndpoint = m(eps.GetBillListEndpoint)
	}
	return eps
}
