// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PayReq struct {
	BillNum              int64    `protobuf:"varint,1,opt,name=bill_num,json=billNum,proto3" json:"bill_num,omitempty"`
	AccountNum           int64    `protobuf:"varint,2,opt,name=account_num,json=accountNum,proto3" json:"account_num,omitempty"`
	PayPassword          string   `protobuf:"bytes,3,opt,name=pay_password,json=payPassword,proto3" json:"pay_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayReq) Reset()         { *m = PayReq{} }
func (m *PayReq) String() string { return proto.CompactTextString(m) }
func (*PayReq) ProtoMessage()    {}
func (*PayReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{0}
}

func (m *PayReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayReq.Unmarshal(m, b)
}
func (m *PayReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayReq.Marshal(b, m, deterministic)
}
func (m *PayReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayReq.Merge(m, src)
}
func (m *PayReq) XXX_Size() int {
	return xxx_messageInfo_PayReq.Size(m)
}
func (m *PayReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayReq proto.InternalMessageInfo

func (m *PayReq) GetBillNum() int64 {
	if m != nil {
		return m.BillNum
	}
	return 0
}

func (m *PayReq) GetAccountNum() int64 {
	if m != nil {
		return m.AccountNum
	}
	return 0
}

func (m *PayReq) GetPayPassword() string {
	if m != nil {
		return m.PayPassword
	}
	return ""
}

type PayResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayResp) Reset()         { *m = PayResp{} }
func (m *PayResp) String() string { return proto.CompactTextString(m) }
func (*PayResp) ProtoMessage()    {}
func (*PayResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6362648dfa63d410, []int{1}
}

func (m *PayResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayResp.Unmarshal(m, b)
}
func (m *PayResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayResp.Marshal(b, m, deterministic)
}
func (m *PayResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayResp.Merge(m, src)
}
func (m *PayResp) XXX_Size() int {
	return xxx_messageInfo_PayResp.Size(m)
}
func (m *PayResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PayResp.DiscardUnknown(m)
}

var xxx_messageInfo_PayResp proto.InternalMessageInfo

func (m *PayResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *PayResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*PayReq)(nil), "pb.PayReq")
	proto.RegisterType((*PayResp)(nil), "pb.PayResp")
}

func init() {
	proto.RegisterFile("payment.proto", fileDescriptor_6362648dfa63d410)
}

var fileDescriptor_6362648dfa63d410 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x4f, 0x4b, 0x6a, 0x85, 0x30,
	0x14, 0x45, 0x05, 0x3f, 0xd7, 0xb6, 0x94, 0x0c, 0x8a, 0xed, 0xa4, 0xd6, 0x91, 0x23, 0x07, 0xb5,
	0x2b, 0xe8, 0x02, 0x8a, 0xa4, 0x0b, 0x90, 0xc4, 0x06, 0x11, 0x12, 0x73, 0x6b, 0x92, 0xf7, 0xc8,
	0xee, 0x1f, 0x46, 0x79, 0xb3, 0xf3, 0xb9, 0x9c, 0x73, 0x2e, 0x3c, 0x22, 0xf3, 0x4a, 0xac, 0xb6,
	0xc3, 0x4d, 0x5b, 0x4d, 0x62, 0xe4, 0xcd, 0x0c, 0xe9, 0xc0, 0x3c, 0x15, 0xff, 0xe4, 0x15, 0x72,
	0xbe, 0x48, 0x39, 0xae, 0x4e, 0x55, 0x51, 0x1d, 0xb5, 0x09, 0xcd, 0x76, 0xfe, 0xe3, 0x14, 0x79,
	0x87, 0x92, 0x4d, 0x93, 0x76, 0xab, 0x0d, 0x6e, 0x1c, 0x5c, 0x38, 0xa5, 0xfd, 0xe0, 0x03, 0x1e,
	0x90, 0xf9, 0x11, 0x99, 0x31, 0x57, 0xbd, 0xfd, 0x55, 0x49, 0x1d, 0xb5, 0x05, 0x2d, 0x91, 0xf9,
	0xe1, 0x94, 0x9a, 0x1e, 0xb2, 0x50, 0x64, 0x90, 0xbc, 0x40, 0x6a, 0x2c, 0xb3, 0xce, 0x84, 0x9e,
	0x9c, 0x9e, 0x8c, 0x3c, 0x43, 0xa2, 0xcc, 0x1c, 0xe2, 0x0b, 0xba, 0xc3, 0xcf, 0x2f, 0x78, 0x1a,
	0x8e, 0xc9, 0xbf, 0x62, 0xbb, 0x2c, 0x93, 0x20, 0x4d, 0x88, 0xf9, 0x5e, 0xa4, 0x24, 0xd0, 0x21,
	0xef, 0x8e, 0xf1, 0x6f, 0xe5, 0x1d, 0x1b, 0xe4, 0x69, 0x78, 0xaf, 0xbf, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x81, 0x13, 0xd1, 0x05, 0xef, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentServiceClient interface {
	PayBill(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) PayBill(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error) {
	out := new(PayResp)
	err := c.cc.Invoke(ctx, "/pb.PaymentService/PayBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
type PaymentServiceServer interface {
	PayBill(context.Context, *PayReq) (*PayResp, error)
}

// UnimplementedPaymentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPaymentServiceServer struct {
}

func (*UnimplementedPaymentServiceServer) PayBill(ctx context.Context, req *PayReq) (*PayResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayBill not implemented")
}

func RegisterPaymentServiceServer(s *grpc.Server, srv PaymentServiceServer) {
	s.RegisterService(&_PaymentService_serviceDesc, srv)
}

func _PaymentService_PayBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).PayBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PaymentService/PayBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).PayBill(ctx, req.(*PayReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PayBill",
			Handler:    _PaymentService_PayBill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment.proto",
}
