// Code generated by protoc-gen-go. DO NOT EDIT.
// source: passenger/pkg/grpc/pb/passenger.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPassengerInfoRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPassengerInfoRequest) Reset()         { *m = GetPassengerInfoRequest{} }
func (m *GetPassengerInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetPassengerInfoRequest) ProtoMessage()    {}
func (*GetPassengerInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a60ecd33327bd37, []int{0}
}

func (m *GetPassengerInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPassengerInfoRequest.Unmarshal(m, b)
}
func (m *GetPassengerInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPassengerInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetPassengerInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPassengerInfoRequest.Merge(m, src)
}
func (m *GetPassengerInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetPassengerInfoRequest.Size(m)
}
func (m *GetPassengerInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPassengerInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPassengerInfoRequest proto.InternalMessageInfo

func (m *GetPassengerInfoRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetPassengerInfoRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetPassengerInfoReply struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	AccountNum           int64    `protobuf:"varint,4,opt,name=account_num,json=accountNum,proto3" json:"account_num,omitempty"`
	Asset                float32  `protobuf:"fixed32,5,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPassengerInfoReply) Reset()         { *m = GetPassengerInfoReply{} }
func (m *GetPassengerInfoReply) String() string { return proto.CompactTextString(m) }
func (*GetPassengerInfoReply) ProtoMessage()    {}
func (*GetPassengerInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a60ecd33327bd37, []int{1}
}

func (m *GetPassengerInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPassengerInfoReply.Unmarshal(m, b)
}
func (m *GetPassengerInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPassengerInfoReply.Marshal(b, m, deterministic)
}
func (m *GetPassengerInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPassengerInfoReply.Merge(m, src)
}
func (m *GetPassengerInfoReply) XXX_Size() int {
	return xxx_messageInfo_GetPassengerInfoReply.Size(m)
}
func (m *GetPassengerInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPassengerInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetPassengerInfoReply proto.InternalMessageInfo

func (m *GetPassengerInfoReply) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetPassengerInfoReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetPassengerInfoReply) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *GetPassengerInfoReply) GetAccountNum() int64 {
	if m != nil {
		return m.AccountNum
	}
	return 0
}

func (m *GetPassengerInfoReply) GetAsset() float32 {
	if m != nil {
		return m.Asset
	}
	return 0
}

type PublishOrderRequest struct {
	PassengerId          int64    `protobuf:"varint,1,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	StartTime            int64    `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination          string   `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	PassengerName        string   `protobuf:"bytes,5,opt,name=passenger_name,json=passengerName,proto3" json:"passenger_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishOrderRequest) Reset()         { *m = PublishOrderRequest{} }
func (m *PublishOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PublishOrderRequest) ProtoMessage()    {}
func (*PublishOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a60ecd33327bd37, []int{2}
}

func (m *PublishOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishOrderRequest.Unmarshal(m, b)
}
func (m *PublishOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishOrderRequest.Marshal(b, m, deterministic)
}
func (m *PublishOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishOrderRequest.Merge(m, src)
}
func (m *PublishOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PublishOrderRequest.Size(m)
}
func (m *PublishOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishOrderRequest proto.InternalMessageInfo

func (m *PublishOrderRequest) GetPassengerId() int64 {
	if m != nil {
		return m.PassengerId
	}
	return 0
}

func (m *PublishOrderRequest) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *PublishOrderRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *PublishOrderRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *PublishOrderRequest) GetPassengerName() string {
	if m != nil {
		return m.PassengerName
	}
	return ""
}

type PublishOrderReply struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	DriverName           string   `protobuf:"bytes,2,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	Location             string   `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Car                  string   `protobuf:"bytes,4,opt,name=car,proto3" json:"car,omitempty"`
	Path                 string   `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishOrderReply) Reset()         { *m = PublishOrderReply{} }
func (m *PublishOrderReply) String() string { return proto.CompactTextString(m) }
func (*PublishOrderReply) ProtoMessage()    {}
func (*PublishOrderReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a60ecd33327bd37, []int{3}
}

func (m *PublishOrderReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishOrderReply.Unmarshal(m, b)
}
func (m *PublishOrderReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishOrderReply.Marshal(b, m, deterministic)
}
func (m *PublishOrderReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishOrderReply.Merge(m, src)
}
func (m *PublishOrderReply) XXX_Size() int {
	return xxx_messageInfo_PublishOrderReply.Size(m)
}
func (m *PublishOrderReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishOrderReply.DiscardUnknown(m)
}

var xxx_messageInfo_PublishOrderReply proto.InternalMessageInfo

func (m *PublishOrderReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *PublishOrderReply) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *PublishOrderReply) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *PublishOrderReply) GetCar() string {
	if m != nil {
		return m.Car
	}
	return ""
}

func (m *PublishOrderReply) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*GetPassengerInfoRequest)(nil), "pb.GetPassengerInfoRequest")
	proto.RegisterType((*GetPassengerInfoReply)(nil), "pb.GetPassengerInfoReply")
	proto.RegisterType((*PublishOrderRequest)(nil), "pb.PublishOrderRequest")
	proto.RegisterType((*PublishOrderReply)(nil), "pb.PublishOrderReply")
}

func init() {
	proto.RegisterFile("passenger/pkg/grpc/pb/passenger.proto", fileDescriptor_2a60ecd33327bd37)
}

var fileDescriptor_2a60ecd33327bd37 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x95, 0x9b, 0x4d, 0xd8, 0x4c, 0x17, 0xb4, 0x18, 0x76, 0x1b, 0x8a, 0x10, 0x21, 0xd2, 0x4a,
	0x3d, 0x35, 0x12, 0xdc, 0xb9, 0xa2, 0x72, 0x28, 0x8b, 0xc5, 0xbd, 0x72, 0x12, 0x93, 0xb5, 0x48,
	0x6c, 0x63, 0x3b, 0xa0, 0xfd, 0x11, 0x70, 0xe5, 0xaf, 0xf0, 0xf3, 0x90, 0x9d, 0x8f, 0x16, 0x5a,
	0x6e, 0xf3, 0xde, 0x58, 0x6f, 0xde, 0xcc, 0x33, 0xdc, 0x28, 0x6a, 0x0c, 0x13, 0x35, 0xd3, 0xb9,
	0xfa, 0x52, 0xe7, 0xb5, 0x56, 0x65, 0xae, 0x8a, 0x7c, 0x62, 0xd7, 0x4a, 0x4b, 0x2b, 0xf1, 0x4c,
	0x15, 0xd9, 0x47, 0x58, 0xbc, 0x63, 0xf6, 0x76, 0xec, 0x6c, 0xc4, 0x67, 0x49, 0xd8, 0xd7, 0x8e,
	0x19, 0x8b, 0x97, 0x70, 0xde, 0x19, 0xa6, 0x05, 0x6d, 0x59, 0x82, 0x52, 0xb4, 0x8a, 0xc9, 0x84,
	0x5d, 0xcf, 0xa9, 0x7d, 0x97, 0xba, 0x4a, 0x66, 0x7d, 0x6f, 0xc4, 0xd9, 0x0f, 0x04, 0x57, 0xc7,
	0x9a, 0xaa, 0xb9, 0xc7, 0x0b, 0x78, 0xe0, 0x14, 0x76, 0xbc, 0xf2, 0x82, 0x01, 0x89, 0x1c, 0xdc,
	0x54, 0x18, 0xc3, 0x99, 0x1f, 0xd3, 0x4b, 0xf9, 0x1a, 0x5f, 0x42, 0x40, 0x6b, 0x96, 0x04, 0x29,
	0x5a, 0x85, 0xc4, 0x95, 0xf8, 0x25, 0xcc, 0x69, 0x59, 0xca, 0x4e, 0xd8, 0x9d, 0xe8, 0xda, 0xe4,
	0xcc, 0x4b, 0xc0, 0x40, 0x6d, 0xbb, 0x16, 0x3f, 0x85, 0xd0, 0x0d, 0xb5, 0x49, 0x98, 0xa2, 0xd5,
	0x8c, 0xf4, 0x20, 0xfb, 0x8d, 0xe0, 0xc9, 0x6d, 0x57, 0x34, 0xdc, 0xdc, 0x7d, 0xd0, 0x15, 0xd3,
	0xe3, 0x7e, 0xaf, 0xe0, 0x62, 0xba, 0xc8, 0xde, 0xd2, 0x7c, 0xe2, 0x36, 0x15, 0x7e, 0x01, 0x60,
	0x2c, 0xd5, 0x76, 0x67, 0xf9, 0xe0, 0x2e, 0x20, 0xb1, 0x67, 0x3e, 0xf1, 0x96, 0xe1, 0x6b, 0x88,
	0xa4, 0xe6, 0x35, 0x17, 0xde, 0x65, 0x4c, 0x06, 0x84, 0x53, 0x98, 0x57, 0xcc, 0x58, 0x2e, 0xa8,
	0xe5, 0x52, 0x78, 0xa3, 0x31, 0x39, 0xa4, 0xf0, 0x0d, 0x3c, 0xda, 0xcf, 0xf6, 0xab, 0x87, 0xfe,
	0xd1, 0xc3, 0x89, 0xdd, 0xd2, 0x96, 0x65, 0x3f, 0x11, 0x3c, 0xfe, 0xdb, 0xba, 0x3b, 0xe3, 0x35,
	0x44, 0xc6, 0x52, 0xdb, 0x19, 0x6f, 0xf9, 0x9c, 0x0c, 0xc8, 0xdd, 0xa7, 0xd2, 0xfc, 0xdb, 0xa8,
	0xd8, 0x1f, 0x13, 0x7a, 0x6a, 0x3b, 0xa4, 0xd6, 0xc8, 0xb2, 0x37, 0xd5, 0x3b, 0x9e, 0xb0, 0x3b,
	0x77, 0x49, 0xf5, 0xe0, 0xd5, 0x95, 0x2e, 0x14, 0x45, 0xed, 0xdd, 0xe0, 0xcc, 0xd7, 0xaf, 0x7f,
	0x21, 0x88, 0xa7, 0x60, 0xf1, 0x7b, 0xb8, 0xfc, 0x37, 0x68, 0xfc, 0x7c, 0xad, 0x8a, 0xf5, 0x7f,
	0xbe, 0xd4, 0xf2, 0xd9, 0xe9, 0xa6, 0x5b, 0xea, 0x2d, 0x5c, 0x1c, 0x6e, 0x8a, 0x17, 0xee, 0xe9,
	0x89, 0xd8, 0x96, 0x57, 0xc7, 0x0d, 0xd5, 0xdc, 0x17, 0x91, 0xff, 0xd3, 0x6f, 0xfe, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x9e, 0x31, 0x48, 0x79, 0xfc, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PassengerClient is the client API for Passenger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PassengerClient interface {
	GetPassengerInfo(ctx context.Context, in *GetPassengerInfoRequest, opts ...grpc.CallOption) (*GetPassengerInfoReply, error)
	PublishOrder(ctx context.Context, in *PublishOrderRequest, opts ...grpc.CallOption) (*PublishOrderReply, error)
}

type passengerClient struct {
	cc grpc.ClientConnInterface
}

func NewPassengerClient(cc grpc.ClientConnInterface) PassengerClient {
	return &passengerClient{cc}
}

func (c *passengerClient) GetPassengerInfo(ctx context.Context, in *GetPassengerInfoRequest, opts ...grpc.CallOption) (*GetPassengerInfoReply, error) {
	out := new(GetPassengerInfoReply)
	err := c.cc.Invoke(ctx, "/pb.Passenger/GetPassengerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerClient) PublishOrder(ctx context.Context, in *PublishOrderRequest, opts ...grpc.CallOption) (*PublishOrderReply, error) {
	out := new(PublishOrderReply)
	err := c.cc.Invoke(ctx, "/pb.Passenger/PublishOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PassengerServer is the server API for Passenger service.
type PassengerServer interface {
	GetPassengerInfo(context.Context, *GetPassengerInfoRequest) (*GetPassengerInfoReply, error)
	PublishOrder(context.Context, *PublishOrderRequest) (*PublishOrderReply, error)
}

// UnimplementedPassengerServer can be embedded to have forward compatible implementations.
type UnimplementedPassengerServer struct {
}

func (*UnimplementedPassengerServer) GetPassengerInfo(ctx context.Context, req *GetPassengerInfoRequest) (*GetPassengerInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPassengerInfo not implemented")
}
func (*UnimplementedPassengerServer) PublishOrder(ctx context.Context, req *PublishOrderRequest) (*PublishOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishOrder not implemented")
}

func RegisterPassengerServer(s *grpc.Server, srv PassengerServer) {
	s.RegisterService(&_Passenger_serviceDesc, srv)
}

func _Passenger_GetPassengerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPassengerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServer).GetPassengerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Passenger/GetPassengerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServer).GetPassengerInfo(ctx, req.(*GetPassengerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Passenger_PublishOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServer).PublishOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Passenger/PublishOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServer).PublishOrder(ctx, req.(*PublishOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Passenger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Passenger",
	HandlerType: (*PassengerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPassengerInfo",
			Handler:    _Passenger_GetPassengerInfo_Handler,
		},
		{
			MethodName: "PublishOrder",
			Handler:    _Passenger_PublishOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "passenger/pkg/grpc/pb/passenger.proto",
}
