// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "notification/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	NoticeTripEndpoint endpoint.Endpoint
	NoticeBillEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.NotificationService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		NoticeBillEndpoint: MakeNoticeBillEndpoint(s),
		NoticeTripEndpoint: MakeNoticeTripEndpoint(s),
	}
	for _, m := range mdw["NoticeTrip"] {
		eps.NoticeTripEndpoint = m(eps.NoticeTripEndpoint)
	}
	for _, m := range mdw["NoticeBill"] {
		eps.NoticeBillEndpoint = m(eps.NoticeBillEndpoint)
	}
	return eps
}
