// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "passenger/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	GetPassengerInfoEndpoint endpoint.Endpoint
	PublishOrderEndpoint     endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.PassengerService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		GetPassengerInfoEndpoint: MakeGetPassengerInfoEndpoint(s),
		PublishOrderEndpoint:     MakePublishOrderEndpoint(s),
	}
	for _, m := range mdw["GetPassengerInfo"] {
		eps.GetPassengerInfoEndpoint = m(eps.GetPassengerInfoEndpoint)
	}
	for _, m := range mdw["PublishOrder"] {
		eps.PublishOrderEndpoint = m(eps.PublishOrderEndpoint)
	}
	return eps
}
