// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "passenger/pkg/endpoint"
	pb "passenger/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	getPassengerInfo grpc.Handler
	publishOrder     grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.PassengerServer {
	return &grpcServer{
		getPassengerInfo: makeGetPassengerInfoHandler(endpoints, options["GetPassengerInfo"]),
		publishOrder:     makePublishOrderHandler(endpoints, options["PublishOrder"]),
	}
}
