// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package service

import (
	endpoint1 "github.com/go-kit/kit/endpoint"
	log "github.com/go-kit/kit/log"
	opentracing "github.com/go-kit/kit/tracing/opentracing"
	"github.com/go-kit/kit/tracing/zipkin"
	grpc "github.com/go-kit/kit/transport/grpc"
	http "github.com/go-kit/kit/transport/http"
	group "github.com/oklog/oklog/pkg/group"
	endpoint "passenger/pkg/endpoint"
	http1 "passenger/pkg/http"
	"pkg/tracing"
)

func createService(endpoints endpoint.Endpoints) (g *group.Group) {
	g = &group.Group{}
	initHttpHandler(endpoints, g)
	initGRPCHandler(endpoints, g)
	return g
}

func defaultHttpOptions(logger log.Logger, tracer *tracing.TracingImpl) map[string][]http.ServerOption {
	options := map[string][]http.ServerOption{
		"GetPassengerInfo": {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "GetPassengerInfo", logger)), zipkin.HTTPServerTrace(tracer.NativeTracer)},
		"PublishOrder":     {http.ServerErrorEncoder(http1.ErrorEncoder), http.ServerErrorLogger(logger), http.ServerBefore(opentracing.HTTPToContext(tracer, "PublishOrder", logger)), zipkin.HTTPServerTrace(tracer.NativeTracer)},
	}
	return options
}
func defaultGRPCOptions(logger log.Logger, tracer *tracing.TracingImpl) map[string][]grpc.ServerOption {
	options := map[string][]grpc.ServerOption{
		"GetPassengerInfo": {grpc.ServerErrorLogger(logger)},
		"PublishOrder":     {grpc.ServerErrorLogger(logger)},
	}
	return options
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint1.Middleware, m endpoint1.Middleware) {
	methods := []string{"GetPassengerInfo", "PublishOrder"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
