// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trip.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TripReq struct {
	PassengerReq         *PassengerReq `protobuf:"bytes,1,opt,name=passenger_req,json=passengerReq,proto3" json:"passenger_req,omitempty"`
	DriverReq            *DriverReq    `protobuf:"bytes,2,opt,name=driver_req,json=driverReq,proto3" json:"driver_req,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TripReq) Reset()         { *m = TripReq{} }
func (m *TripReq) String() string { return proto.CompactTextString(m) }
func (*TripReq) ProtoMessage()    {}
func (*TripReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{0}
}

func (m *TripReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TripReq.Unmarshal(m, b)
}
func (m *TripReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TripReq.Marshal(b, m, deterministic)
}
func (m *TripReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TripReq.Merge(m, src)
}
func (m *TripReq) XXX_Size() int {
	return xxx_messageInfo_TripReq.Size(m)
}
func (m *TripReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TripReq.DiscardUnknown(m)
}

var xxx_messageInfo_TripReq proto.InternalMessageInfo

func (m *TripReq) GetPassengerReq() *PassengerReq {
	if m != nil {
		return m.PassengerReq
	}
	return nil
}

func (m *TripReq) GetDriverReq() *DriverReq {
	if m != nil {
		return m.DriverReq
	}
	return nil
}

type Trip struct {
	TripNum              int64    `protobuf:"varint,1,opt,name=trip_num,json=tripNum,proto3" json:"trip_num,omitempty"`
	PassengerId          int64    `protobuf:"varint,2,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	DriverId             int64    `protobuf:"varint,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	PassengerName        string   `protobuf:"bytes,4,opt,name=passenger_name,json=passengerName,proto3" json:"passenger_name,omitempty"`
	DriverName           string   `protobuf:"bytes,5,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	StartTime            int64    `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64    `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Origin               string   `protobuf:"bytes,8,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination          string   `protobuf:"bytes,9,opt,name=destination,proto3" json:"destination,omitempty"`
	Car                  string   `protobuf:"bytes,10,opt,name=car,proto3" json:"car,omitempty"`
	Path                 string   `protobuf:"bytes,11,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trip) Reset()         { *m = Trip{} }
func (m *Trip) String() string { return proto.CompactTextString(m) }
func (*Trip) ProtoMessage()    {}
func (*Trip) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{1}
}

func (m *Trip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trip.Unmarshal(m, b)
}
func (m *Trip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trip.Marshal(b, m, deterministic)
}
func (m *Trip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trip.Merge(m, src)
}
func (m *Trip) XXX_Size() int {
	return xxx_messageInfo_Trip.Size(m)
}
func (m *Trip) XXX_DiscardUnknown() {
	xxx_messageInfo_Trip.DiscardUnknown(m)
}

var xxx_messageInfo_Trip proto.InternalMessageInfo

func (m *Trip) GetTripNum() int64 {
	if m != nil {
		return m.TripNum
	}
	return 0
}

func (m *Trip) GetPassengerId() int64 {
	if m != nil {
		return m.PassengerId
	}
	return 0
}

func (m *Trip) GetDriverId() int64 {
	if m != nil {
		return m.DriverId
	}
	return 0
}

func (m *Trip) GetPassengerName() string {
	if m != nil {
		return m.PassengerName
	}
	return ""
}

func (m *Trip) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *Trip) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Trip) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Trip) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Trip) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Trip) GetCar() string {
	if m != nil {
		return m.Car
	}
	return ""
}

func (m *Trip) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type TripResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Trip                 *Trip    `protobuf:"bytes,2,opt,name=trip,proto3" json:"trip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TripResp) Reset()         { *m = TripResp{} }
func (m *TripResp) String() string { return proto.CompactTextString(m) }
func (*TripResp) ProtoMessage()    {}
func (*TripResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a31f58919dc2e020, []int{2}
}

func (m *TripResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TripResp.Unmarshal(m, b)
}
func (m *TripResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TripResp.Marshal(b, m, deterministic)
}
func (m *TripResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TripResp.Merge(m, src)
}
func (m *TripResp) XXX_Size() int {
	return xxx_messageInfo_TripResp.Size(m)
}
func (m *TripResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TripResp.DiscardUnknown(m)
}

var xxx_messageInfo_TripResp proto.InternalMessageInfo

func (m *TripResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *TripResp) GetTrip() *Trip {
	if m != nil {
		return m.Trip
	}
	return nil
}

func init() {
	proto.RegisterType((*TripReq)(nil), "pb.TripReq")
	proto.RegisterType((*Trip)(nil), "pb.Trip")
	proto.RegisterType((*TripResp)(nil), "pb.TripResp")
}

func init() {
	proto.RegisterFile("trip.proto", fileDescriptor_a31f58919dc2e020)
}

var fileDescriptor_a31f58919dc2e020 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x52, 0xc1, 0x6e, 0xea, 0x30,
	0x10, 0x14, 0x24, 0x8f, 0x24, 0x1b, 0x78, 0x0f, 0xf9, 0xf0, 0x94, 0xd2, 0x56, 0xa5, 0xa8, 0x95,
	0x38, 0x54, 0x1c, 0x40, 0xbd, 0xf7, 0x50, 0xa9, 0xe2, 0x82, 0xaa, 0x94, 0x7b, 0x64, 0xf0, 0x8a,
	0xfa, 0x10, 0xc7, 0xb1, 0x0d, 0x3f, 0xd8, 0x1f, 0xab, 0xbc, 0x09, 0x84, 0xdb, 0xce, 0xcc, 0xce,
	0x4e, 0xd6, 0x1b, 0x00, 0x67, 0xa4, 0x5e, 0x68, 0x53, 0xb9, 0x8a, 0xf5, 0xf5, 0x6e, 0xf2, 0x4f,
	0x73, 0x6b, 0x51, 0x1d, 0xd0, 0x34, 0xe4, 0x64, 0x28, 0x8c, 0x3c, 0x9d, 0xd1, 0x4c, 0x41, 0xb4,
	0x35, 0x52, 0xe7, 0x58, 0xb3, 0x57, 0x18, 0x5d, 0x7a, 0x0b, 0x83, 0x75, 0xd6, 0x9b, 0xf6, 0xe6,
	0xe9, 0x72, 0xbc, 0xd0, 0xbb, 0xc5, 0xe7, 0x59, 0xc8, 0xb1, 0xce, 0x87, 0xfa, 0x0a, 0xb1, 0x17,
	0x80, 0x66, 0x22, 0x79, 0xfa, 0xe4, 0x19, 0x79, 0xcf, 0x3b, 0xb1, 0xde, 0x90, 0x88, 0x73, 0x39,
	0xfb, 0xe9, 0x43, 0xe8, 0x03, 0xd9, 0x0d, 0xc4, 0xfe, 0x4b, 0x0b, 0x75, 0x2c, 0x29, 0x28, 0xc8,
	0x23, 0x8f, 0x37, 0xc7, 0x92, 0x3d, 0x42, 0x97, 0x50, 0x48, 0x41, 0x33, 0x83, 0x3c, 0xbd, 0x70,
	0x6b, 0xc1, 0x6e, 0xa1, 0x9d, 0xe9, 0xf5, 0x80, 0xf4, 0xb8, 0x21, 0xd6, 0x82, 0x3d, 0xc3, 0xdf,
	0xce, 0xaf, 0x78, 0x89, 0x59, 0x38, 0xed, 0xcd, 0x93, 0xbc, 0x5b, 0x6f, 0xc3, 0x4b, 0x64, 0x0f,
	0x90, 0xb6, 0x33, 0xa8, 0xe7, 0x0f, 0xf5, 0xb4, 0xbb, 0x50, 0xc3, 0x3d, 0x80, 0x75, 0xdc, 0xb8,
	0xc2, 0xc9, 0x12, 0xb3, 0x01, 0xa5, 0x24, 0xc4, 0x6c, 0x65, 0x89, 0x7e, 0x03, 0x54, 0xa2, 0x11,
	0xa3, 0x66, 0x03, 0x54, 0x82, 0xa4, 0xff, 0x30, 0xa8, 0x8c, 0x3c, 0x48, 0x95, 0xc5, 0x34, 0xb5,
	0x45, 0x6c, 0x0a, 0xa9, 0x40, 0xeb, 0xa4, 0xe2, 0x4e, 0x56, 0x2a, 0x4b, 0x48, 0xbc, 0xa6, 0xd8,
	0x18, 0x82, 0x3d, 0x37, 0x19, 0x90, 0xe2, 0x4b, 0xc6, 0x20, 0xd4, 0xdc, 0x7d, 0x67, 0x29, 0x51,
	0x54, 0xcf, 0xde, 0x20, 0x6e, 0xae, 0x66, 0xb5, 0xcf, 0xb2, 0x8e, 0xbb, 0xa3, 0xa5, 0x67, 0x8c,
	0xf3, 0x16, 0xb1, 0x3b, 0x08, 0xfd, 0x83, 0xb6, 0x17, 0x89, 0xfd, 0x45, 0xc8, 0x43, 0xec, 0x72,
	0x05, 0xa9, 0x47, 0x5f, 0x68, 0x4e, 0x72, 0x8f, 0xec, 0x09, 0xa2, 0x0f, 0x54, 0x74, 0x98, 0xf4,
	0xd2, 0x89, 0xf5, 0x64, 0xd8, 0x01, 0xab, 0x77, 0x03, 0xfa, 0x67, 0x56, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xbd, 0xc9, 0x25, 0xaa, 0x64, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TripServiceClient is the client API for TripService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TripServiceClient interface {
	GenTrip(ctx context.Context, in *TripReq, opts ...grpc.CallOption) (*TripResp, error)
}

type tripServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTripServiceClient(cc grpc.ClientConnInterface) TripServiceClient {
	return &tripServiceClient{cc}
}

func (c *tripServiceClient) GenTrip(ctx context.Context, in *TripReq, opts ...grpc.CallOption) (*TripResp, error) {
	out := new(TripResp)
	err := c.cc.Invoke(ctx, "/pb.TripService/GenTrip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TripServiceServer is the server API for TripService service.
type TripServiceServer interface {
	GenTrip(context.Context, *TripReq) (*TripResp, error)
}

// UnimplementedTripServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTripServiceServer struct {
}

func (*UnimplementedTripServiceServer) GenTrip(ctx context.Context, req *TripReq) (*TripResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenTrip not implemented")
}

func RegisterTripServiceServer(s *grpc.Server, srv TripServiceServer) {
	s.RegisterService(&_TripService_serviceDesc, srv)
}

func _TripService_GenTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TripReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GenTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TripService/GenTrip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GenTrip(ctx, req.(*TripReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _TripService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TripService",
	HandlerType: (*TripServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenTrip",
			Handler:    _TripService_GenTrip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trip.proto",
}
