// Code generated by protoc-gen-go. DO NOT EDIT.
// source: passenger.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PassengerInfoReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassengerInfoReq) Reset()         { *m = PassengerInfoReq{} }
func (m *PassengerInfoReq) String() string { return proto.CompactTextString(m) }
func (*PassengerInfoReq) ProtoMessage()    {}
func (*PassengerInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59870f8f4446d21a, []int{0}
}

func (m *PassengerInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerInfoReq.Unmarshal(m, b)
}
func (m *PassengerInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerInfoReq.Marshal(b, m, deterministic)
}
func (m *PassengerInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerInfoReq.Merge(m, src)
}
func (m *PassengerInfoReq) XXX_Size() int {
	return xxx_messageInfo_PassengerInfoReq.Size(m)
}
func (m *PassengerInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerInfoReq proto.InternalMessageInfo

func (m *PassengerInfoReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PassengerInfoReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type PassengerInfoResp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	AccountNum           int64    `protobuf:"varint,4,opt,name=account_num,json=accountNum,proto3" json:"account_num,omitempty"`
	Asset                float32  `protobuf:"fixed32,5,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassengerInfoResp) Reset()         { *m = PassengerInfoResp{} }
func (m *PassengerInfoResp) String() string { return proto.CompactTextString(m) }
func (*PassengerInfoResp) ProtoMessage()    {}
func (*PassengerInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59870f8f4446d21a, []int{1}
}

func (m *PassengerInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerInfoResp.Unmarshal(m, b)
}
func (m *PassengerInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerInfoResp.Marshal(b, m, deterministic)
}
func (m *PassengerInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerInfoResp.Merge(m, src)
}
func (m *PassengerInfoResp) XXX_Size() int {
	return xxx_messageInfo_PassengerInfoResp.Size(m)
}
func (m *PassengerInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerInfoResp proto.InternalMessageInfo

func (m *PassengerInfoResp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PassengerInfoResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PassengerInfoResp) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *PassengerInfoResp) GetAccountNum() int64 {
	if m != nil {
		return m.AccountNum
	}
	return 0
}

func (m *PassengerInfoResp) GetAsset() float32 {
	if m != nil {
		return m.Asset
	}
	return 0
}

type PassengerReq struct {
	PassengerId          int64    `protobuf:"varint,1,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	StartTime            int64    `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination          string   `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	PassengerName        string   `protobuf:"bytes,5,opt,name=passenger_name,json=passengerName,proto3" json:"passenger_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassengerReq) Reset()         { *m = PassengerReq{} }
func (m *PassengerReq) String() string { return proto.CompactTextString(m) }
func (*PassengerReq) ProtoMessage()    {}
func (*PassengerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59870f8f4446d21a, []int{2}
}

func (m *PassengerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerReq.Unmarshal(m, b)
}
func (m *PassengerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerReq.Marshal(b, m, deterministic)
}
func (m *PassengerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerReq.Merge(m, src)
}
func (m *PassengerReq) XXX_Size() int {
	return xxx_messageInfo_PassengerReq.Size(m)
}
func (m *PassengerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerReq.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerReq proto.InternalMessageInfo

func (m *PassengerReq) GetPassengerId() int64 {
	if m != nil {
		return m.PassengerId
	}
	return 0
}

func (m *PassengerReq) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *PassengerReq) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *PassengerReq) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *PassengerReq) GetPassengerName() string {
	if m != nil {
		return m.PassengerName
	}
	return ""
}

type PassengerResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	DriverName           string   `protobuf:"bytes,2,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	Location             string   `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Car                  string   `protobuf:"bytes,4,opt,name=car,proto3" json:"car,omitempty"`
	Path                 string   `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassengerResp) Reset()         { *m = PassengerResp{} }
func (m *PassengerResp) String() string { return proto.CompactTextString(m) }
func (*PassengerResp) ProtoMessage()    {}
func (*PassengerResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_59870f8f4446d21a, []int{3}
}

func (m *PassengerResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassengerResp.Unmarshal(m, b)
}
func (m *PassengerResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassengerResp.Marshal(b, m, deterministic)
}
func (m *PassengerResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassengerResp.Merge(m, src)
}
func (m *PassengerResp) XXX_Size() int {
	return xxx_messageInfo_PassengerResp.Size(m)
}
func (m *PassengerResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PassengerResp.DiscardUnknown(m)
}

var xxx_messageInfo_PassengerResp proto.InternalMessageInfo

func (m *PassengerResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *PassengerResp) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *PassengerResp) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *PassengerResp) GetCar() string {
	if m != nil {
		return m.Car
	}
	return ""
}

func (m *PassengerResp) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*PassengerInfoReq)(nil), "pb.PassengerInfoReq")
	proto.RegisterType((*PassengerInfoResp)(nil), "pb.PassengerInfoResp")
	proto.RegisterType((*PassengerReq)(nil), "pb.PassengerReq")
	proto.RegisterType((*PassengerResp)(nil), "pb.PassengerResp")
}

func init() {
	proto.RegisterFile("passenger.proto", fileDescriptor_59870f8f4446d21a)
}

var fileDescriptor_59870f8f4446d21a = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0xe5, 0x66, 0x53, 0x36, 0xd3, 0x2e, 0x64, 0x47, 0x0b, 0x44, 0x95, 0x10, 0x21, 0x12,
	0x52, 0x4f, 0x3d, 0xd0, 0x07, 0xe0, 0x88, 0xca, 0xa1, 0x54, 0x86, 0x7b, 0xe5, 0x24, 0xa6, 0xb5,
	0xd4, 0xd8, 0xc6, 0x76, 0xca, 0x2b, 0x00, 0x6f, 0xc3, 0x1b, 0x22, 0x3b, 0x69, 0xfa, 0x47, 0xdc,
	0xe6, 0xfb, 0x6c, 0x7f, 0xf3, 0xb3, 0x3d, 0xf0, 0x42, 0x33, 0x6b, 0xb9, 0xdc, 0x71, 0xb3, 0xd0,
	0x46, 0x39, 0x85, 0x23, 0x5d, 0x16, 0x9f, 0x21, 0xdd, 0x9c, 0xec, 0x95, 0xfc, 0xae, 0x28, 0xff,
	0x81, 0x33, 0xb8, 0x6f, 0x2d, 0x37, 0x92, 0x35, 0x3c, 0x23, 0x39, 0x99, 0x27, 0x74, 0xd0, 0x7e,
	0xcd, 0xc7, 0xfc, 0x54, 0xa6, 0xce, 0x46, 0xdd, 0xda, 0x49, 0x17, 0xbf, 0x09, 0x3c, 0xde, 0x84,
	0x59, 0x8d, 0xaf, 0xe1, 0x99, 0x3f, 0xbd, 0x15, 0x75, 0x08, 0x8b, 0xe8, 0xd8, 0xcb, 0x55, 0x8d,
	0x08, 0x77, 0xa1, 0x45, 0x17, 0x13, 0x6a, 0x4c, 0x21, 0x62, 0x3b, 0x9e, 0x45, 0x39, 0x99, 0xc7,
	0xd4, 0x97, 0xf8, 0x16, 0x26, 0xac, 0xaa, 0x54, 0x2b, 0xdd, 0x56, 0xb6, 0x4d, 0x76, 0x17, 0x22,
	0xa0, 0xb7, 0xd6, 0x6d, 0x83, 0x4f, 0x10, 0xfb, 0x9e, 0x2e, 0x8b, 0x73, 0x32, 0x1f, 0xd1, 0x4e,
	0x14, 0x7f, 0x09, 0x4c, 0x07, 0x16, 0x7f, 0xa9, 0x77, 0x30, 0x1d, 0xee, 0x7f, 0x66, 0x99, 0x0c,
	0xde, 0xaa, 0xc6, 0x37, 0x00, 0xd6, 0x31, 0xe3, 0xb6, 0x4e, 0xf4, 0x58, 0x11, 0x4d, 0x82, 0xf3,
	0x4d, 0x34, 0x1c, 0x5f, 0xc1, 0x58, 0x19, 0xb1, 0x13, 0x32, 0xe0, 0x25, 0xb4, 0x57, 0x98, 0xc3,
	0xa4, 0xe6, 0xd6, 0x09, 0xc9, 0x9c, 0x50, 0x32, 0x10, 0x26, 0xf4, 0xd2, 0xc2, 0xf7, 0xf0, 0xfc,
	0xdc, 0x3b, 0xdc, 0x39, 0x0e, 0x9b, 0x1e, 0x06, 0x77, 0xcd, 0x1a, 0x5e, 0xfc, 0x21, 0xf0, 0x70,
	0xc1, 0x6c, 0xb5, 0x6f, 0x69, 0x1d, 0x73, 0xad, 0x0d, 0xb8, 0xf7, 0xb4, 0x57, 0xfe, 0x51, 0x6a,
	0x23, 0x8e, 0xa7, 0xb4, 0xee, 0x05, 0xa1, 0xb3, 0xd6, 0xfd, 0x37, 0x1d, 0x54, 0xd5, 0x01, 0x75,
	0xb4, 0x83, 0xf6, 0x6f, 0x5c, 0x31, 0xd3, 0x73, 0xfa, 0xd2, 0xff, 0x84, 0x66, 0x6e, 0xdf, 0x53,
	0x85, 0xfa, 0xc3, 0x2f, 0x72, 0x31, 0x19, 0x5f, 0xb9, 0x39, 0x8a, 0x8a, 0xe3, 0x47, 0x48, 0x3f,
	0x71, 0x77, 0xf5, 0xc7, 0xf8, 0xb4, 0xd0, 0xe5, 0xe2, 0x76, 0x86, 0x66, 0x2f, 0xff, 0xe3, 0x5a,
	0x8d, 0x4b, 0x98, 0x6e, 0xda, 0xf2, 0x20, 0xec, 0xfe, 0x8b, 0xa9, 0xb9, 0xc1, 0xf4, 0x6a, 0x9b,
	0x3f, 0xf8, 0x78, 0xe3, 0x58, 0x5d, 0x8e, 0xc3, 0xb8, 0x2e, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xe0, 0xa5, 0x4e, 0x2a, 0xc1, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PassengerServiceClient is the client API for PassengerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PassengerServiceClient interface {
	GetPassengerInfo(ctx context.Context, in *PassengerInfoReq, opts ...grpc.CallOption) (*PassengerInfoResp, error)
	PublishOrder(ctx context.Context, in *PassengerReq, opts ...grpc.CallOption) (*PassengerResp, error)
}

type passengerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPassengerServiceClient(cc grpc.ClientConnInterface) PassengerServiceClient {
	return &passengerServiceClient{cc}
}

func (c *passengerServiceClient) GetPassengerInfo(ctx context.Context, in *PassengerInfoReq, opts ...grpc.CallOption) (*PassengerInfoResp, error) {
	out := new(PassengerInfoResp)
	err := c.cc.Invoke(ctx, "/pb.PassengerService/GetPassengerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passengerServiceClient) PublishOrder(ctx context.Context, in *PassengerReq, opts ...grpc.CallOption) (*PassengerResp, error) {
	out := new(PassengerResp)
	err := c.cc.Invoke(ctx, "/pb.PassengerService/PublishOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PassengerServiceServer is the server API for PassengerService service.
type PassengerServiceServer interface {
	GetPassengerInfo(context.Context, *PassengerInfoReq) (*PassengerInfoResp, error)
	PublishOrder(context.Context, *PassengerReq) (*PassengerResp, error)
}

// UnimplementedPassengerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPassengerServiceServer struct {
}

func (*UnimplementedPassengerServiceServer) GetPassengerInfo(ctx context.Context, req *PassengerInfoReq) (*PassengerInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPassengerInfo not implemented")
}
func (*UnimplementedPassengerServiceServer) PublishOrder(ctx context.Context, req *PassengerReq) (*PassengerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishOrder not implemented")
}

func RegisterPassengerServiceServer(s *grpc.Server, srv PassengerServiceServer) {
	s.RegisterService(&_PassengerService_serviceDesc, srv)
}

func _PassengerService_GetPassengerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassengerInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).GetPassengerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PassengerService/GetPassengerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).GetPassengerInfo(ctx, req.(*PassengerInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassengerService_PublishOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassengerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassengerServiceServer).PublishOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PassengerService/PublishOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassengerServiceServer).PublishOrder(ctx, req.(*PassengerReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PassengerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PassengerService",
	HandlerType: (*PassengerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPassengerInfo",
			Handler:    _PassengerService_GetPassengerInfo_Handler,
		},
		{
			MethodName: "PublishOrder",
			Handler:    _PassengerService_PublishOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "passenger.proto",
}
