// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NoticeTripReq struct {
	Trip                 *Trip    `protobuf:"bytes,1,opt,name=trip,proto3" json:"trip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeTripReq) Reset()         { *m = NoticeTripReq{} }
func (m *NoticeTripReq) String() string { return proto.CompactTextString(m) }
func (*NoticeTripReq) ProtoMessage()    {}
func (*NoticeTripReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{0}
}

func (m *NoticeTripReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeTripReq.Unmarshal(m, b)
}
func (m *NoticeTripReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeTripReq.Marshal(b, m, deterministic)
}
func (m *NoticeTripReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeTripReq.Merge(m, src)
}
func (m *NoticeTripReq) XXX_Size() int {
	return xxx_messageInfo_NoticeTripReq.Size(m)
}
func (m *NoticeTripReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeTripReq.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeTripReq proto.InternalMessageInfo

func (m *NoticeTripReq) GetTrip() *Trip {
	if m != nil {
		return m.Trip
	}
	return nil
}

type NoticeTripResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeTripResp) Reset()         { *m = NoticeTripResp{} }
func (m *NoticeTripResp) String() string { return proto.CompactTextString(m) }
func (*NoticeTripResp) ProtoMessage()    {}
func (*NoticeTripResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{1}
}

func (m *NoticeTripResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeTripResp.Unmarshal(m, b)
}
func (m *NoticeTripResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeTripResp.Marshal(b, m, deterministic)
}
func (m *NoticeTripResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeTripResp.Merge(m, src)
}
func (m *NoticeTripResp) XXX_Size() int {
	return xxx_messageInfo_NoticeTripResp.Size(m)
}
func (m *NoticeTripResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeTripResp.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeTripResp proto.InternalMessageInfo

func (m *NoticeTripResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *NoticeTripResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type NoticeBillReq struct {
	Bill                 *Bill    `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeBillReq) Reset()         { *m = NoticeBillReq{} }
func (m *NoticeBillReq) String() string { return proto.CompactTextString(m) }
func (*NoticeBillReq) ProtoMessage()    {}
func (*NoticeBillReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{2}
}

func (m *NoticeBillReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeBillReq.Unmarshal(m, b)
}
func (m *NoticeBillReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeBillReq.Marshal(b, m, deterministic)
}
func (m *NoticeBillReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeBillReq.Merge(m, src)
}
func (m *NoticeBillReq) XXX_Size() int {
	return xxx_messageInfo_NoticeBillReq.Size(m)
}
func (m *NoticeBillReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeBillReq.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeBillReq proto.InternalMessageInfo

func (m *NoticeBillReq) GetBill() *Bill {
	if m != nil {
		return m.Bill
	}
	return nil
}

type NoticeBillResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeBillResp) Reset()         { *m = NoticeBillResp{} }
func (m *NoticeBillResp) String() string { return proto.CompactTextString(m) }
func (*NoticeBillResp) ProtoMessage()    {}
func (*NoticeBillResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_736a457d4a5efa07, []int{3}
}

func (m *NoticeBillResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeBillResp.Unmarshal(m, b)
}
func (m *NoticeBillResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeBillResp.Marshal(b, m, deterministic)
}
func (m *NoticeBillResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeBillResp.Merge(m, src)
}
func (m *NoticeBillResp) XXX_Size() int {
	return xxx_messageInfo_NoticeBillResp.Size(m)
}
func (m *NoticeBillResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeBillResp.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeBillResp proto.InternalMessageInfo

func (m *NoticeBillResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *NoticeBillResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*NoticeTripReq)(nil), "pb.NoticeTripReq")
	proto.RegisterType((*NoticeTripResp)(nil), "pb.NoticeTripResp")
	proto.RegisterType((*NoticeBillReq)(nil), "pb.NoticeBillReq")
	proto.RegisterType((*NoticeBillResp)(nil), "pb.NoticeBillResp")
}

func init() {
	proto.RegisterFile("notification.proto", fileDescriptor_736a457d4a5efa07)
}

var fileDescriptor_736a457d4a5efa07 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0xcb, 0x2f, 0xc9,
	0x4c, 0xcb, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x2a, 0x48, 0x92, 0xe2, 0x2a, 0x29, 0xca, 0x2c, 0x80, 0xf0, 0xa5, 0x78, 0x93, 0x32, 0x73, 0x72,
	0x32, 0xf3, 0xd2, 0x21, 0x5c, 0x25, 0x5d, 0x2e, 0x5e, 0xbf, 0xfc, 0x92, 0xcc, 0xe4, 0xd4, 0x90,
	0xa2, 0xcc, 0x82, 0xa0, 0xd4, 0x42, 0x21, 0x19, 0x2e, 0x16, 0x90, 0x6a, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0x6e, 0x23, 0x0e, 0xbd, 0x82, 0x24, 0x3d, 0xb0, 0x14, 0x58, 0x54, 0xc9, 0x8a, 0x8b, 0x0f,
	0x59, 0x79, 0x71, 0x81, 0x90, 0x18, 0x17, 0x5b, 0x71, 0x49, 0x62, 0x49, 0x69, 0x31, 0x58, 0x07,
	0x47, 0x10, 0x94, 0x27, 0x24, 0xc0, 0xc5, 0x9c, 0x5b, 0x9c, 0x2e, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1,
	0x19, 0x04, 0x62, 0x22, 0xac, 0x72, 0xca, 0xcc, 0xc9, 0x81, 0x5a, 0x05, 0x72, 0x0c, 0xb2, 0x55,
	0x60, 0x29, 0xb0, 0x28, 0xc2, 0x2a, 0x88, 0x72, 0x52, 0xac, 0x32, 0xaa, 0x84, 0x59, 0x15, 0x9c,
	0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0x64, 0xcc, 0xc5, 0x85, 0x70, 0xb7, 0x90, 0x20, 0xc8, 0x2a,
	0x14, 0x6f, 0x4b, 0x09, 0xa1, 0x0b, 0x15, 0x17, 0x20, 0x34, 0x81, 0x5c, 0x80, 0xac, 0x09, 0xea,
	0x01, 0x64, 0x4d, 0x30, 0x47, 0x26, 0xb1, 0x81, 0xc3, 0xd5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x4a, 0xec, 0xc6, 0x39, 0x8c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NoticeServiceClient is the client API for NoticeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NoticeServiceClient interface {
	NoticeTrip(ctx context.Context, in *NoticeTripReq, opts ...grpc.CallOption) (*NoticeTripResp, error)
	NoticeBill(ctx context.Context, in *NoticeBillReq, opts ...grpc.CallOption) (*NoticeBillResp, error)
}

type noticeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNoticeServiceClient(cc grpc.ClientConnInterface) NoticeServiceClient {
	return &noticeServiceClient{cc}
}

func (c *noticeServiceClient) NoticeTrip(ctx context.Context, in *NoticeTripReq, opts ...grpc.CallOption) (*NoticeTripResp, error) {
	out := new(NoticeTripResp)
	err := c.cc.Invoke(ctx, "/pb.NoticeService/NoticeTrip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noticeServiceClient) NoticeBill(ctx context.Context, in *NoticeBillReq, opts ...grpc.CallOption) (*NoticeBillResp, error) {
	out := new(NoticeBillResp)
	err := c.cc.Invoke(ctx, "/pb.NoticeService/NoticeBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoticeServiceServer is the server API for NoticeService service.
type NoticeServiceServer interface {
	NoticeTrip(context.Context, *NoticeTripReq) (*NoticeTripResp, error)
	NoticeBill(context.Context, *NoticeBillReq) (*NoticeBillResp, error)
}

// UnimplementedNoticeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNoticeServiceServer struct {
}

func (*UnimplementedNoticeServiceServer) NoticeTrip(ctx context.Context, req *NoticeTripReq) (*NoticeTripResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NoticeTrip not implemented")
}
func (*UnimplementedNoticeServiceServer) NoticeBill(ctx context.Context, req *NoticeBillReq) (*NoticeBillResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NoticeBill not implemented")
}

func RegisterNoticeServiceServer(s *grpc.Server, srv NoticeServiceServer) {
	s.RegisterService(&_NoticeService_serviceDesc, srv)
}

func _NoticeService_NoticeTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeTripReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServiceServer).NoticeTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NoticeService/NoticeTrip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServiceServer).NoticeTrip(ctx, req.(*NoticeTripReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoticeService_NoticeBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeBillReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServiceServer).NoticeBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.NoticeService/NoticeBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServiceServer).NoticeBill(ctx, req.(*NoticeBillReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _NoticeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.NoticeService",
	HandlerType: (*NoticeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NoticeTrip",
			Handler:    _NoticeService_NoticeTrip_Handler,
		},
		{
			MethodName: "NoticeBill",
			Handler:    _NoticeService_NoticeBill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}
