// Code generated by protoc-gen-go. DO NOT EDIT.
// source: billing.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BillMsg struct {
	BillNum              int64    `protobuf:"varint,1,opt,name=bill_num,json=billNum,proto3" json:"bill_num,omitempty"`
	Price                float32  `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	StartTime            int64    `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64    `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Origin               string   `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination          string   `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
	PassengerName        string   `protobuf:"bytes,7,opt,name=passenger_name,json=passengerName,proto3" json:"passenger_name,omitempty"`
	DriverName           string   `protobuf:"bytes,8,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	Payed                bool     `protobuf:"varint,9,opt,name=payed,proto3" json:"payed,omitempty"`
	PassengerId          int64    `protobuf:"varint,10,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"`
	DriverId             int64    `protobuf:"varint,11,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BillMsg) Reset()         { *m = BillMsg{} }
func (m *BillMsg) String() string { return proto.CompactTextString(m) }
func (*BillMsg) ProtoMessage()    {}
func (*BillMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{0}
}

func (m *BillMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BillMsg.Unmarshal(m, b)
}
func (m *BillMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BillMsg.Marshal(b, m, deterministic)
}
func (m *BillMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BillMsg.Merge(m, src)
}
func (m *BillMsg) XXX_Size() int {
	return xxx_messageInfo_BillMsg.Size(m)
}
func (m *BillMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BillMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BillMsg proto.InternalMessageInfo

func (m *BillMsg) GetBillNum() int64 {
	if m != nil {
		return m.BillNum
	}
	return 0
}

func (m *BillMsg) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BillMsg) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *BillMsg) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *BillMsg) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *BillMsg) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *BillMsg) GetPassengerName() string {
	if m != nil {
		return m.PassengerName
	}
	return ""
}

func (m *BillMsg) GetDriverName() string {
	if m != nil {
		return m.DriverName
	}
	return ""
}

func (m *BillMsg) GetPayed() bool {
	if m != nil {
		return m.Payed
	}
	return false
}

func (m *BillMsg) GetPassengerId() int64 {
	if m != nil {
		return m.PassengerId
	}
	return 0
}

func (m *BillMsg) GetDriverId() int64 {
	if m != nil {
		return m.DriverId
	}
	return 0
}

type GenBillRequest struct {
	BillMsg              *BillMsg `protobuf:"bytes,1,opt,name=bill_msg,json=billMsg,proto3" json:"bill_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenBillRequest) Reset()         { *m = GenBillRequest{} }
func (m *GenBillRequest) String() string { return proto.CompactTextString(m) }
func (*GenBillRequest) ProtoMessage()    {}
func (*GenBillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{1}
}

func (m *GenBillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenBillRequest.Unmarshal(m, b)
}
func (m *GenBillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenBillRequest.Marshal(b, m, deterministic)
}
func (m *GenBillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenBillRequest.Merge(m, src)
}
func (m *GenBillRequest) XXX_Size() int {
	return xxx_messageInfo_GenBillRequest.Size(m)
}
func (m *GenBillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenBillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenBillRequest proto.InternalMessageInfo

func (m *GenBillRequest) GetBillMsg() *BillMsg {
	if m != nil {
		return m.BillMsg
	}
	return nil
}

type GenBillReply struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	BillMsg              *BillMsg `protobuf:"bytes,2,opt,name=bill_msg,json=billMsg,proto3" json:"bill_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenBillReply) Reset()         { *m = GenBillReply{} }
func (m *GenBillReply) String() string { return proto.CompactTextString(m) }
func (*GenBillReply) ProtoMessage()    {}
func (*GenBillReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{2}
}

func (m *GenBillReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenBillReply.Unmarshal(m, b)
}
func (m *GenBillReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenBillReply.Marshal(b, m, deterministic)
}
func (m *GenBillReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenBillReply.Merge(m, src)
}
func (m *GenBillReply) XXX_Size() int {
	return xxx_messageInfo_GenBillReply.Size(m)
}
func (m *GenBillReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GenBillReply.DiscardUnknown(m)
}

var xxx_messageInfo_GenBillReply proto.InternalMessageInfo

func (m *GenBillReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *GenBillReply) GetBillMsg() *BillMsg {
	if m != nil {
		return m.BillMsg
	}
	return nil
}

type GetBillRequest struct {
	BillNum              int64    `protobuf:"varint,1,opt,name=bill_num,json=billNum,proto3" json:"bill_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBillRequest) Reset()         { *m = GetBillRequest{} }
func (m *GetBillRequest) String() string { return proto.CompactTextString(m) }
func (*GetBillRequest) ProtoMessage()    {}
func (*GetBillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{3}
}

func (m *GetBillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBillRequest.Unmarshal(m, b)
}
func (m *GetBillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBillRequest.Marshal(b, m, deterministic)
}
func (m *GetBillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBillRequest.Merge(m, src)
}
func (m *GetBillRequest) XXX_Size() int {
	return xxx_messageInfo_GetBillRequest.Size(m)
}
func (m *GetBillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBillRequest proto.InternalMessageInfo

func (m *GetBillRequest) GetBillNum() int64 {
	if m != nil {
		return m.BillNum
	}
	return 0
}

type GetBillReply struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	BillMsg              *BillMsg `protobuf:"bytes,2,opt,name=bill_msg,json=billMsg,proto3" json:"bill_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBillReply) Reset()         { *m = GetBillReply{} }
func (m *GetBillReply) String() string { return proto.CompactTextString(m) }
func (*GetBillReply) ProtoMessage()    {}
func (*GetBillReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{4}
}

func (m *GetBillReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBillReply.Unmarshal(m, b)
}
func (m *GetBillReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBillReply.Marshal(b, m, deterministic)
}
func (m *GetBillReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBillReply.Merge(m, src)
}
func (m *GetBillReply) XXX_Size() int {
	return xxx_messageInfo_GetBillReply.Size(m)
}
func (m *GetBillReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBillReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetBillReply proto.InternalMessageInfo

func (m *GetBillReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *GetBillReply) GetBillMsg() *BillMsg {
	if m != nil {
		return m.BillMsg
	}
	return nil
}

type GetBillListRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBillListRequest) Reset()         { *m = GetBillListRequest{} }
func (m *GetBillListRequest) String() string { return proto.CompactTextString(m) }
func (*GetBillListRequest) ProtoMessage()    {}
func (*GetBillListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{5}
}

func (m *GetBillListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBillListRequest.Unmarshal(m, b)
}
func (m *GetBillListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBillListRequest.Marshal(b, m, deterministic)
}
func (m *GetBillListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBillListRequest.Merge(m, src)
}
func (m *GetBillListRequest) XXX_Size() int {
	return xxx_messageInfo_GetBillListRequest.Size(m)
}
func (m *GetBillListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBillListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBillListRequest proto.InternalMessageInfo

func (m *GetBillListRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetBillListReply struct {
	BillList             []*BillMsg `protobuf:"bytes,1,rep,name=bill_list,json=billList,proto3" json:"bill_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetBillListReply) Reset()         { *m = GetBillListReply{} }
func (m *GetBillListReply) String() string { return proto.CompactTextString(m) }
func (*GetBillListReply) ProtoMessage()    {}
func (*GetBillListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{6}
}

func (m *GetBillListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBillListReply.Unmarshal(m, b)
}
func (m *GetBillListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBillListReply.Marshal(b, m, deterministic)
}
func (m *GetBillListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBillListReply.Merge(m, src)
}
func (m *GetBillListReply) XXX_Size() int {
	return xxx_messageInfo_GetBillListReply.Size(m)
}
func (m *GetBillListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBillListReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetBillListReply proto.InternalMessageInfo

func (m *GetBillListReply) GetBillList() []*BillMsg {
	if m != nil {
		return m.BillList
	}
	return nil
}

type SetPayedAndGetPriceRequest struct {
	BillNum              int64    `protobuf:"varint,1,opt,name=bill_num,json=billNum,proto3" json:"bill_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPayedAndGetPriceRequest) Reset()         { *m = SetPayedAndGetPriceRequest{} }
func (m *SetPayedAndGetPriceRequest) String() string { return proto.CompactTextString(m) }
func (*SetPayedAndGetPriceRequest) ProtoMessage()    {}
func (*SetPayedAndGetPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{7}
}

func (m *SetPayedAndGetPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPayedAndGetPriceRequest.Unmarshal(m, b)
}
func (m *SetPayedAndGetPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPayedAndGetPriceRequest.Marshal(b, m, deterministic)
}
func (m *SetPayedAndGetPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPayedAndGetPriceRequest.Merge(m, src)
}
func (m *SetPayedAndGetPriceRequest) XXX_Size() int {
	return xxx_messageInfo_SetPayedAndGetPriceRequest.Size(m)
}
func (m *SetPayedAndGetPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPayedAndGetPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPayedAndGetPriceRequest proto.InternalMessageInfo

func (m *SetPayedAndGetPriceRequest) GetBillNum() int64 {
	if m != nil {
		return m.BillNum
	}
	return 0
}

type SetPayedAndGetPriceReply struct {
	Price                float32  `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPayedAndGetPriceReply) Reset()         { *m = SetPayedAndGetPriceReply{} }
func (m *SetPayedAndGetPriceReply) String() string { return proto.CompactTextString(m) }
func (*SetPayedAndGetPriceReply) ProtoMessage()    {}
func (*SetPayedAndGetPriceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_958db8ba491a6b57, []int{8}
}

func (m *SetPayedAndGetPriceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPayedAndGetPriceReply.Unmarshal(m, b)
}
func (m *SetPayedAndGetPriceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPayedAndGetPriceReply.Marshal(b, m, deterministic)
}
func (m *SetPayedAndGetPriceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPayedAndGetPriceReply.Merge(m, src)
}
func (m *SetPayedAndGetPriceReply) XXX_Size() int {
	return xxx_messageInfo_SetPayedAndGetPriceReply.Size(m)
}
func (m *SetPayedAndGetPriceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPayedAndGetPriceReply.DiscardUnknown(m)
}

var xxx_messageInfo_SetPayedAndGetPriceReply proto.InternalMessageInfo

func (m *SetPayedAndGetPriceReply) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*BillMsg)(nil), "pb.BillMsg")
	proto.RegisterType((*GenBillRequest)(nil), "pb.GenBillRequest")
	proto.RegisterType((*GenBillReply)(nil), "pb.GenBillReply")
	proto.RegisterType((*GetBillRequest)(nil), "pb.GetBillRequest")
	proto.RegisterType((*GetBillReply)(nil), "pb.GetBillReply")
	proto.RegisterType((*GetBillListRequest)(nil), "pb.GetBillListRequest")
	proto.RegisterType((*GetBillListReply)(nil), "pb.GetBillListReply")
	proto.RegisterType((*SetPayedAndGetPriceRequest)(nil), "pb.SetPayedAndGetPriceRequest")
	proto.RegisterType((*SetPayedAndGetPriceReply)(nil), "pb.SetPayedAndGetPriceReply")
}

func init() {
	proto.RegisterFile("billing.proto", fileDescriptor_958db8ba491a6b57)
}

var fileDescriptor_958db8ba491a6b57 = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0x56, 0x52, 0xd6, 0x8f, 0x37, 0xdb, 0x34, 0xcc, 0x54, 0x4c, 0x29, 0x23, 0x44, 0x0c, 0x45,
	0x9b, 0xd2, 0xa0, 0x71, 0x00, 0x4d, 0x5c, 0xe0, 0x32, 0x55, 0xa2, 0xd5, 0x14, 0xe0, 0x5c, 0xa5,
	0xd8, 0x8a, 0x2c, 0x25, 0x4e, 0x88, 0x5d, 0xa4, 0x6a, 0x9a, 0x84, 0xf8, 0x0b, 0x9c, 0xf8, 0x4f,
	0xdc, 0xf8, 0x0b, 0xfc, 0x10, 0x64, 0x3b, 0x6d, 0xd3, 0xad, 0x45, 0x1c, 0xb8, 0xe5, 0xfd, 0x7a,
	0x9e, 0xc7, 0xcf, 0x6b, 0x07, 0xf6, 0xa6, 0x2c, 0x4d, 0x19, 0x4f, 0x06, 0x45, 0x99, 0xcb, 0x1c,
	0xd9, 0xc5, 0xb4, 0xd7, 0x4f, 0xf2, 0x3c, 0x49, 0x69, 0x18, 0x17, 0x2c, 0x8c, 0x39, 0xcf, 0x65,
	0x2c, 0x59, 0xce, 0x85, 0xe9, 0xf0, 0x7e, 0xda, 0xd0, 0x7a, 0xcb, 0xd2, 0x74, 0x24, 0x12, 0xf4,
	0x00, 0xda, 0x6a, 0x7c, 0xc2, 0x67, 0x19, 0xb6, 0x5c, 0xcb, 0x6f, 0x44, 0x2d, 0x15, 0x8f, 0x67,
	0x19, 0x3a, 0x84, 0x9d, 0xa2, 0x64, 0x9f, 0x28, 0xb6, 0x5d, 0xcb, 0xb7, 0x23, 0x13, 0xa0, 0x47,
	0x00, 0x42, 0xc6, 0xa5, 0x9c, 0x48, 0x96, 0x51, 0xdc, 0xd0, 0x23, 0x1d, 0x9d, 0xf9, 0xc0, 0x32,
	0xaa, 0xf0, 0x28, 0x27, 0xa6, 0x78, 0xc7, 0xe0, 0x51, 0x4e, 0x74, 0xa9, 0x0b, 0xcd, 0xbc, 0x64,
	0x09, 0xe3, 0x78, 0xc7, 0xb5, 0xfc, 0x4e, 0x54, 0x45, 0xc8, 0x05, 0x87, 0x50, 0x21, 0x19, 0xd7,
	0x22, 0x71, 0x53, 0x17, 0xeb, 0x29, 0x74, 0x0c, 0xfb, 0x45, 0x2c, 0x04, 0xe5, 0x09, 0x2d, 0x27,
	0x3c, 0xce, 0x28, 0x6e, 0xe9, 0xa6, 0xbd, 0x65, 0x76, 0x1c, 0x67, 0x14, 0x3d, 0x06, 0x87, 0x94,
	0xec, 0xcb, 0xa2, 0xa7, 0xad, 0x7b, 0xc0, 0xa4, 0x74, 0x83, 0x3a, 0x51, 0x3c, 0xa7, 0x04, 0x77,
	0x5c, 0xcb, 0x6f, 0x47, 0x26, 0x40, 0x4f, 0x60, 0x77, 0x85, 0xce, 0x08, 0x06, 0x2d, 0xdb, 0x59,
	0xe6, 0x86, 0x04, 0x3d, 0x84, 0x4e, 0x85, 0xcc, 0x08, 0x76, 0x74, 0xbd, 0x6d, 0x12, 0x43, 0xe2,
	0xbd, 0x82, 0xfd, 0x0b, 0xca, 0x95, 0xa1, 0x11, 0xfd, 0x3c, 0xa3, 0x42, 0xa2, 0x67, 0x95, 0xa9,
	0x99, 0x48, 0xb4, 0xa9, 0xce, 0x99, 0x33, 0x28, 0xa6, 0x83, 0xca, 0x73, 0xe3, 0xf0, 0x48, 0x24,
	0xde, 0x18, 0x76, 0x97, 0x93, 0x45, 0x3a, 0x57, 0x0e, 0x09, 0x19, 0xcb, 0x99, 0xd0, 0x53, 0xed,
	0xa8, 0x8a, 0xd6, 0xf0, 0xec, 0xbf, 0xe0, 0x9d, 0x2a, 0x25, 0xb2, 0xae, 0x64, 0xfb, 0x7a, 0x0d,
	0xb9, 0xfc, 0x7f, 0xe4, 0x01, 0xa0, 0x0a, 0xef, 0x1d, 0x13, 0x72, 0x21, 0xe0, 0x3e, 0xb4, 0x66,
	0xc2, 0xf8, 0x66, 0xf8, 0x9b, 0x2a, 0x1c, 0x12, 0xef, 0x35, 0x1c, 0xac, 0xb5, 0x2b, 0x09, 0x3e,
	0x74, 0x34, 0x55, 0xca, 0x84, 0xc4, 0x96, 0xdb, 0xb8, 0xc9, 0xa5, 0x85, 0xa8, 0x76, 0xef, 0x25,
	0xf4, 0xde, 0x53, 0x79, 0xa9, 0xf6, 0xf7, 0x86, 0x93, 0x0b, 0x2a, 0x2f, 0xd5, 0xe5, 0xfc, 0x87,
	0x53, 0x3f, 0x07, 0xbc, 0x71, 0x50, 0xd1, 0x6f, 0xbc, 0xf0, 0x67, 0x3f, 0x1a, 0xe6, 0xb5, 0x30,
	0x9e, 0xa0, 0x11, 0xb4, 0xaa, 0x85, 0x21, 0xa4, 0x84, 0xad, 0xef, 0xbd, 0x77, 0xb0, 0x96, 0x2b,
	0xd2, 0xb9, 0xd7, 0xff, 0xf6, 0xeb, 0xf7, 0x77, 0xbb, 0xeb, 0xdd, 0x0d, 0xab, 0x47, 0x1a, 0x26,
	0x94, 0x07, 0xea, 0xfb, 0xdc, 0x3a, 0x41, 0x14, 0x9c, 0x9a, 0x07, 0xa8, 0x6b, 0xc6, 0x6f, 0x7a,
	0xd8, 0x3b, 0xbc, 0x95, 0x57, 0xd0, 0xbe, 0x86, 0xf6, 0x90, 0x5b, 0x83, 0x96, 0x1a, 0x3a, 0x50,
	0xfe, 0x85, 0x57, 0x95, 0xef, 0xd7, 0xe8, 0xa3, 0x52, 0x2d, 0xeb, 0xaa, 0xe5, 0x06, 0xd5, 0xab,
	0xab, 0xe0, 0x3d, 0xd5, 0xd0, 0x47, 0xa8, 0x7f, 0x0b, 0x3a, 0xbc, 0x5a, 0x18, 0x7b, 0x8d, 0xbe,
	0x5a, 0x70, 0x6f, 0x83, 0x97, 0xe8, 0x48, 0xe1, 0x6d, 0xdf, 0x4e, 0xaf, 0xbf, 0xb5, 0xae, 0xb8,
	0x4f, 0x35, 0xf7, 0xb1, 0xb7, 0x3a, 0x96, 0xa0, 0x32, 0xd0, 0x2f, 0x35, 0x88, 0x39, 0x09, 0x94,
	0x12, 0xbd, 0x98, 0x73, 0xeb, 0x64, 0xda, 0xd4, 0x3f, 0xb4, 0x17, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x74, 0xc0, 0x87, 0xda, 0x03, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BillingClient is the client API for Billing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BillingClient interface {
	GenBill(ctx context.Context, in *GenBillRequest, opts ...grpc.CallOption) (*GenBillReply, error)
	GetBillList(ctx context.Context, in *GetBillListRequest, opts ...grpc.CallOption) (*GetBillListReply, error)
	GetBill(ctx context.Context, in *GetBillRequest, opts ...grpc.CallOption) (*GetBillReply, error)
	SetPayedAndGetPrice(ctx context.Context, in *SetPayedAndGetPriceRequest, opts ...grpc.CallOption) (*SetPayedAndGetPriceReply, error)
}

type billingClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingClient(cc grpc.ClientConnInterface) BillingClient {
	return &billingClient{cc}
}

func (c *billingClient) GenBill(ctx context.Context, in *GenBillRequest, opts ...grpc.CallOption) (*GenBillReply, error) {
	out := new(GenBillReply)
	err := c.cc.Invoke(ctx, "/pb.Billing/GenBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingClient) GetBillList(ctx context.Context, in *GetBillListRequest, opts ...grpc.CallOption) (*GetBillListReply, error) {
	out := new(GetBillListReply)
	err := c.cc.Invoke(ctx, "/pb.Billing/GetBillList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingClient) GetBill(ctx context.Context, in *GetBillRequest, opts ...grpc.CallOption) (*GetBillReply, error) {
	out := new(GetBillReply)
	err := c.cc.Invoke(ctx, "/pb.Billing/GetBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingClient) SetPayedAndGetPrice(ctx context.Context, in *SetPayedAndGetPriceRequest, opts ...grpc.CallOption) (*SetPayedAndGetPriceReply, error) {
	out := new(SetPayedAndGetPriceReply)
	err := c.cc.Invoke(ctx, "/pb.Billing/SetPayedAndGetPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServer is the server API for Billing service.
type BillingServer interface {
	GenBill(context.Context, *GenBillRequest) (*GenBillReply, error)
	GetBillList(context.Context, *GetBillListRequest) (*GetBillListReply, error)
	GetBill(context.Context, *GetBillRequest) (*GetBillReply, error)
	SetPayedAndGetPrice(context.Context, *SetPayedAndGetPriceRequest) (*SetPayedAndGetPriceReply, error)
}

// UnimplementedBillingServer can be embedded to have forward compatible implementations.
type UnimplementedBillingServer struct {
}

func (*UnimplementedBillingServer) GenBill(ctx context.Context, req *GenBillRequest) (*GenBillReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenBill not implemented")
}
func (*UnimplementedBillingServer) GetBillList(ctx context.Context, req *GetBillListRequest) (*GetBillListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBillList not implemented")
}
func (*UnimplementedBillingServer) GetBill(ctx context.Context, req *GetBillRequest) (*GetBillReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBill not implemented")
}
func (*UnimplementedBillingServer) SetPayedAndGetPrice(ctx context.Context, req *SetPayedAndGetPriceRequest) (*SetPayedAndGetPriceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPayedAndGetPrice not implemented")
}

func RegisterBillingServer(s *grpc.Server, srv BillingServer) {
	s.RegisterService(&_Billing_serviceDesc, srv)
}

func _Billing_GenBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).GenBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Billing/GenBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).GenBill(ctx, req.(*GenBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Billing_GetBillList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).GetBillList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Billing/GetBillList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).GetBillList(ctx, req.(*GetBillListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Billing_GetBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).GetBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Billing/GetBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).GetBill(ctx, req.(*GetBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Billing_SetPayedAndGetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPayedAndGetPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).SetPayedAndGetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Billing/SetPayedAndGetPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).SetPayedAndGetPrice(ctx, req.(*SetPayedAndGetPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Billing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Billing",
	HandlerType: (*BillingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenBill",
			Handler:    _Billing_GenBill_Handler,
		},
		{
			MethodName: "GetBillList",
			Handler:    _Billing_GetBillList_Handler,
		},
		{
			MethodName: "GetBill",
			Handler:    _Billing_GetBill_Handler,
		},
		{
			MethodName: "SetPayedAndGetPrice",
			Handler:    _Billing_SetPayedAndGetPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing.proto",
}
